debts/urls.py
from django.urls import path
from .views import home, my_transactions, user_transactions, transaction_processor, download_summary_csv, sync_to_dropbox

urlpatterns = [
    path('', home, name='home'),

    path('my-transactions/', my_transactions, name='my-transaction'),
    path('user-transactions/<str:username>/', user_transactions, name='user-transaction'),

    path('transaction-processor/<str:username>/<int:transaction_id>/', transaction_processor, name='new-transaction'),
    path('transaction-processor/<str:username>/', transaction_processor, name='new-transaction'),
    path('transaction-processor/', transaction_processor, name='new-transaction'),
    
    path('download-summary-csv/', download_summary_csv, name="download-summary-csv"),
    path('sync-to-dropbox/', sync_to_dropbox, name="sync-to-dropbox")

    # path('text-db/', text_to_db, name='textdb')
]

debts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils import timezone


class TransactionType(models.Model):
    title = models.CharField(max_length=20)

    def __str__(self):
        return f'{self.title}'

class Transaction(models.Model):
    debtor = models.ForeignKey(User, on_delete=models.CASCADE)
    entered_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='entered_by')
    transaction_type = models.ForeignKey(TransactionType, on_delete=models.CASCADE)
    amount = models.FloatField()
    remarks = models.TextField(blank=True)
    transaction_date = models.DateTimeField()
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f'{self.debtor.username}: amount ({self.amount}): transaction_type ({self.transaction_type.title}): dated ({self.transaction_date})'

    def absolute_url(self):
        pass

debts/forms.py
from django import forms
from django.forms import ModelForm, RadioSelect, widgets
from .models import Transaction


class TransactionCreationForm(forms.Form):
    CHOICES = [('1', 'Lent'), ('2', 'Recovered')]

    transaction_type_id = forms.CharField(label='Transaction Type', widget=forms.RadioSelect(choices=CHOICES), initial=1)
    amount = forms.FloatField(label='Total Amount')
    # transaction_date = forms.DateField(label='Transaction Date', widget=forms.SelectDateWidget)
    remarks = forms.CharField(label='Remarks', widget=forms.Textarea, required=False)


class TransactionModalForm(ModelForm):

    class Meta:
        model = Transaction
        fields = ['transaction_date', 'transaction_type', 'amount', 'remarks']

        widgets = {
            'transaction_type': RadioSelect(),
            'transaction_date': widgets.DateInput(attrs={'type': 'date'})
        }

debts/views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponse
from .models import Transaction
from django.contrib.auth.models import User, Group
from django.db.models import Sum, Q, FloatField
from django.db.models.functions import Coalesce
from django.contrib.auth.decorators import login_required, user_passes_test
from .forms import TransactionModalForm
from django.contrib import messages
import csv
import datetime
import dropbox
import os
from django.conf import settings


# check if a given user is super_user
def _super_user_test(user):
    return user.is_superuser


@login_required
@user_passes_test(_super_user_test, login_url='my-transactions/')
def home(request):

    # get the debtors group
    debtor_group = Group.objects.get(pk=1)

    # user-wise debts summary
    debtors = debtor_group.user_set.annotate(
        total_lent=Coalesce(Sum('transaction__amount', filter=Q(transaction__transaction_type_id=1)), 0, output_field=FloatField()),
        total_received=Coalesce(Sum('transaction__amount', filter=Q(transaction__transaction_type_id=2)), 0, output_field=FloatField()),
        total_balance=Coalesce(Sum('transaction__amount', filter=Q(transaction__transaction_type_id=1)), 0, output_field=FloatField()) - Coalesce(Sum('transaction__amount', filter=Q(transaction__transaction_type_id=2)), 0, output_field=FloatField())
    ).order_by('first_name')

    # overall debt summary
    overall_summary = Transaction.objects.aggregate(
        grand_total_lent = Coalesce(Sum('amount', filter=Q(transaction_type_id=1)), 0, output_field=FloatField()),
        grand_total_received=Coalesce(Sum('amount', filter=Q(transaction_type_id=2)), 0, output_field=FloatField()),
        grand_total_balance=Coalesce(Sum('amount', filter=Q(transaction_type_id=1)), 0, output_field=FloatField()) - Coalesce(Sum('amount', filter=Q(transaction_type_id=2)), 0, output_field=FloatField())
    )

    context = {
        'debtors': debtors,
        'overall_summary': overall_summary
    }

    return render(request, 'debts/home.html', context)


# debtor (users) homepage to track their debt status
@login_required
def my_transactions(request):

    # current user and current user's transactions
    user = request.user
    user_transactions = user.transaction_set.all().order_by('-transaction_date')

    # overall summary of the current user
    overall_summary = user.transaction_set.aggregate(
        grand_total_lent=Coalesce(Sum('amount', filter=Q(transaction_type_id=1)), 0, output_field=FloatField()),
        grand_total_received=Coalesce(Sum('amount', filter=Q(transaction_type_id=2)), 0, output_field=FloatField()),
        grand_total_balance=Coalesce(Sum('amount', filter=Q(transaction_type_id=1)), 0,
                                     output_field=FloatField()) - Coalesce(
            Sum('amount', filter=Q(transaction_type_id=2)), 0, output_field=FloatField())
    )

    context = {
        'transactions': user_transactions,
        'overall_summary' : overall_summary,
        'current_user': user
    }

    return render(request, 'debts/my_transactions.html', context)


@login_required
@user_passes_test(_super_user_test, login_url='my-transactions/')
def user_transactions(request, username):

    # current user and current user's transactions
    user = User.objects.filter(username=username).first()
    user_transactions = user.transaction_set.all().order_by('-transaction_date')

    # overall summary of the current user
    overall_summary = user.transaction_set.aggregate(
        grand_total_lent=Coalesce(Sum('amount', filter=Q(transaction_type_id=1)), 0, output_field=FloatField()),
        grand_total_received=Coalesce(Sum('amount', filter=Q(transaction_type_id=2)), 0, output_field=FloatField()),
        grand_total_balance=Coalesce(Sum('amount', filter=Q(transaction_type_id=1)), 0,
                                     output_field=FloatField()) - Coalesce(
            Sum('amount', filter=Q(transaction_type_id=2)), 0, output_field=FloatField())
    )

    context = {
        'transactions': user_transactions,
        'overall_summary' : overall_summary,
        'current_user': user
    }

    return render(request, 'debts/my_transactions.html', context)


@login_required
@user_passes_test(_super_user_test, login_url='my-transactions/')
def transaction_processor(request, username=None, transaction_id=None):

    # if we are on edit transaction
    if transaction_id is not None:
        trx = get_object_or_404(Transaction, pk=transaction_id)
    else:
        trx = Transaction()

    form = TransactionModalForm(request.POST or None, instance=trx)
    
    if username is None:
        # get all the debtors for group transaction
        debtor_group = Group.objects.get(pk=1)
        debtors = debtor_group.user_set.order_by('first_name').all()
        transaction_mode = 'group'
    else:
        # single user transaction
        debtors = User.objects.filter(username=username).first()
        transaction_mode = 'single'

    if request.method == 'POST':
        # form = TransactionModalForm(request.POST)
        if form.is_valid():

            if request.POST.get('transaction_mode') == 'group':
                selected_debtors = request.POST.getlist('debtor_id')
                print(selected_debtors)
                total_amount = request.POST.get('amount')
                per_head = float(total_amount) / len(selected_debtors)

                for debtor in selected_debtors:
                    print(debtor)
                    trx = form.save(commit=False)
                    trx.pk = None
                    trx.entered_by = request.user
                    trx.debtor_id = debtor
                    trx.amount = per_head
                    trx.save()

            else:
                trx = form.save(commit=False)
                trx.entered_by = request.user
                trx.debtor_id = request.POST.get('debtor_id')
                trx.save()

            messages.success(request, 'Transaction saved successfully')
            return redirect('home')

    context = {
        'debtors': debtors,
        'transaction_mode': transaction_mode,
        'form': form
    }

    return render(request, 'debts/transaction_form.html', context)


@login_required
@user_passes_test(_super_user_test, login_url='my-transactions/')
def download_summary_csv(request):
    # get the debtors group
    debtor_group = Group.objects.get(pk=1)

    # user-wise debts summary
    debtors = debtor_group.user_set.annotate(
        total_lent=Coalesce(Sum('transaction__amount', filter=Q(transaction__transaction_type_id=1)), 0, output_field=FloatField()),
        total_received=Coalesce(Sum('transaction__amount', filter=Q(transaction__transaction_type_id=2)), 0, output_field=FloatField()),
        total_balance=Coalesce(Sum('transaction__amount', filter=Q(transaction__transaction_type_id=1)), 0, output_field=FloatField()) -
                      Coalesce(Sum('transaction__amount', filter=Q(transaction__transaction_type_id=2)), 0, output_field=FloatField())
    ).order_by('first_name')

    date_now = datetime.datetime.now()
    filename = 'summary_'+date_now.strftime("%Y-%m-%d %H-%M-%S %f")+".csv"
    response = HttpResponse(
        content_type='text/csv',
        headers={'Content-Disposition': f'attachment; filename="{filename}"'},
    )

    writer = csv.writer(response)

    writer.writerow(['Name', 'Total Lent', 'Total Recovered', 'Balance'])

    for debtor in debtors:
        writer.writerow([
            debtor.first_name+" "+debtor.last_name+" @"+debtor.username,
            round(debtor.total_lent, 2),
            round(debtor.total_received, 2),
            round(debtor.total_balance, 2)
        ])

    return response


@login_required
@user_passes_test(_super_user_test, login_url='my-transactions/')
def sync_to_dropbox(request):

    access_token = settings.DBX_ACCESS_TOKEN

    # get debts summary
    debtor_group = Group.objects.get(pk=1)
    debtors = debtor_group.user_set.annotate(
        total_lent=Coalesce(Sum('transaction__amount', filter=Q(transaction__transaction_type_id=1)), 0,
                            output_field=FloatField()),
        total_received=Coalesce(Sum('transaction__amount', filter=Q(transaction__transaction_type_id=2)), 0,
                                output_field=FloatField()),
        total_balance=Coalesce(Sum('transaction__amount', filter=Q(transaction__transaction_type_id=1)), 0,
                               output_field=FloatField()) -
                      Coalesce(Sum('transaction__amount', filter=Q(transaction__transaction_type_id=2)), 0,
                               output_field=FloatField())
    ).order_by('first_name')

    # create a unique dated file name to be saved to dropbox
    date_now = datetime.datetime.now()
    filename = settings.IS_DUMMY+'summary_' + date_now.strftime("%Y-%m-%d %H-%M-%S %f") + ".csv"
    full_path = os.path.join(settings.MEDIA_ROOT+filename)

    row_list = []
    row_list.append(['Name', 'Total Lent', 'Total Recovered', 'Balance'])
    for debtor in debtors:
        row_list.append([
            debtor.first_name + " " + debtor.last_name + " @" + debtor.username,
            round(debtor.total_lent, 2),
            round(debtor.total_received, 2),
            round(debtor.total_balance, 2)
        ])

    # save csv file to media
    with open(full_path, 'w', newline='') as file:
        writer = csv.writer(file)
        writer.writerows(row_list)


    # open file, save to dropbox and then delete it form media
    dbx = dropbox.Dropbox(access_token)
    with open(full_path, "rb") as f:
        try:
            dbx.files_upload(f.read(), '/'+filename, mute=True)
            os.remove(full_path)
            messages.success(request, 'Sync to dropbox')
        except:
            messages.error(request, 'Dropbox sync failed')

    return redirect('home')





# def text_to_db(request):
#
#     import os
#     from datetime import datetime
#

debts/templates/debts/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />

    <link rel="stylesheet" href="{% static 'debts/custom.css' %}">
    <link rel="stylesheet" href="{% static 'debts/fontawesome-free-5.15.3-web/css/all.min.css' %}">

    <title>Debt Manager</title>
</head>
<body>


<div class="container">

<div class="row">

    <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2 main-content">


        <div class="header-bar">

            <div class="row">
                <div class="col-md-6 sol-sm-12">
                    <h2>Welcome {{ user.username }}</h2>
                </div>

                <div class="col-md-6 col-sm-12 text-right">

                    {% if user.is_superuser %}
                        <a href="{% url 'download-summary-csv' %}" class="btn btn-sm btn-success text-white">
                            <i class="fa fa-download"></i> CSV
                        </a>
                    {% else %}
                        <button class="btn btn-sm btn-success text-white">
                            <i class="fa fa-download"></i> CSV
                        </button>
                    {% endif %}

                    {% if user.is_superuser %}
                    <a href="{% url 'sync-to-dropbox' %}" class="btn btn-sm btn-info text-white">
                        <i class="fa fa-upload"></i> Dropbox
                    </a>
                    {% endif %}

                    <a href="{% url 'profile' %}" class="btn btn-sm btn-warning text-white">
                        <i class="fa fa-user"></i> Profile
                    </a>

                    {% if user.is_authenticated %}
                        <a href="{% url 'user-logout' %}" class="btn btn-sm btn-danger text-white">
                            <i class="fa fa-lock"></i> Logout
                        </a>
                    {% endif %}
                </div>
            </div>


            {% if overall_summary %}
            <div class="row">
                <div class="col-12">

                    (<span class="text-success">Total Lent: {{ overall_summary.grand_total_lent|floatformat:2 }} PKR</span> -
                    <span class="text-danger">Total Recovered: {{ overall_summary.grand_total_received|floatformat:2 }} PKR</span>) =
                    {% if overall_summary.grand_total_balance > 0 %}
                        <span class="text-success">Balance: {{ overall_summary.grand_total_balance|floatformat:2 }} PKR</span>
                    {% else %}
                        <span class="text-danger">Balance: {{ overall_summary.grand_total_balance|floatformat:2 }} PKR</span>
                    {% endif %}

                </div>
            </div>
            {% endif %}


        </div>

        <div class="content-render" style="padding-top: 0px;">

            {% if messages %}
                <div class="mb-3">
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}">{{ message }}</div>
                {% endfor %}
                </div>
            {% endif %}

            {% block content %} {% endblock content %}
        </div>


        {% if user.is_superuser and request.resolver_match.url_name == 'home' %}
        <div class="footer">
            <a href="{% url 'new-transaction' %}" class="btn btn-sm btn-info text-white">
                <i class="fa fa-list"></i> Group Transaction
            </a>
            <a href="{% url 'user-register' %}" class="btn btn-sm btn-warning text-white">
                <i class="fa fa-user"></i> New Member
            </a>
        </div>
    {% endif %}


    </div>



</div>



</div>

<script
  src="https://code.jquery.com/jquery-2.2.4.min.js"
  integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44="
  crossorigin="anonymous"></script>


<!-- Optional JavaScript; choose one of the two! -->

<!-- Option 1: Bootstrap Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>

<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>

<!-- Option 2: Separate Popper and Bootstrap JS -->
<!--
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
-->


<script type="text/javascript">
    $(document).ready(function() {
        $('.select2').select2();
    });
</script>
</body>
</html>

debts/templates/debts/home.html
{% extends 'debts/base.html' %}

{% block content %}

    <div class="row">
        <div class="col-12">

            {% for debtor in debtors %}
            <div class="debtor">
                <div class="row">
                    <div class="col-7">
                        <h6 class="mb-0">
                            <a href="{% url 'user-transaction' debtor.username %}">
                                {{ debtor.first_name}} {{ debtor.last_name }} <br>
                                <small class="text-muted text-small">@{{ debtor.username }}</small>
                            </a>
                        </h6>
                        <span class="text-small text-muted">
                            <strong>Total lent / Received:</strong> <span class="text-success"> +{{ debtor.total_lent|default_if_none:"0"|floatformat:2 }} PKR</span> / <span class="text-danger"> -{{ debtor.total_received|default_if_none:"0"|floatformat:2 }} PKR</span>
                        </span>
                    </div>

                    <div class="col-5 text-right">

                        {% if debtor.total_balance > 0 %}
                            <h5 class="text-success">+{{ debtor.total_balance|floatformat:2 }} PKR</h5>
                        {% elif debtor.total_balance < 0 %}
                            <h5 class="text-danger">{{ debtor.total_balance|floatformat:2 }} PKR</h5>
                        {% else %}
                            <h5 class="text-success">0 PKR</h5>
                        {% endif %}


                        <a href="{% url 'new-transaction' username=debtor.username %}" class="text-danger btn btn-sm btn-outline-danger">
                            <small><i class="fa fa-plus"></i> New</small>
                        </a>

                        <a href="{% url 'user-transaction' username=debtor.username %}" class="text-info btn btn-sm btn-outline-info">
                            <small><i class="fa fa-list-ol"></i> Details</small>
                        </a>

                    </div>
                </div>
            </div>
            {% endfor %}


        </div>
    </div>


{% endblock %}

debts/templates/debts/my_transactions.html
{% extends 'debts/base.html' %}

{% block content %}

{#    {{ transactions.values }}#}
    <div class="row">
        <div class="col-12">

            {% if user.is_superuser %}
                <div class="text-small- text-muted mb-2">
                    <a href="{% url 'home' %}">Home</a> /
                    <span>{{ current_user.first_name }} {{ current_user.last_name }} (@{{ current_user.username }})</span>
                </div>
            {% endif %}

            {% for trns in transactions %}
            <div class="debtor">
                <div class="row">
                    <div class="col-7">

                        {% if trns.transaction_type_id == 1 %}
                            <h5 class="text-success">+{{ trns.amount|floatformat:2 }}</h5>
                        {% else %}
                            <h5 class="text-danger">-{{ trns.amount|floatformat:2 }}</h5>
                        {% endif %}

                        <span class="text-small text-muted">
                            {{ trns.remarks }}
                        </span>
                    </div>

                    <div class="col-5 text-right">

                        <h6>
                            {{ trns.transaction_date|date:'d F, Y' }}
                        </h6>


                        {% if user.is_superuser %}
                            <a href="{% url 'new-transaction' username=current_user.username transaction_id=trns.id %}" class="btn btn-sm btn-info text-white">
                                <i class="fa fa-edit"></i>
                            </a>

                            <a href="#" class="btn btn-sm btn-danger text-white">
                                <i class="fa fa-trash"></i>
                            </a>
                        {% endif %}

                    </div>
                </div>
            </div>
            {% endfor %}


        </div>
    </div>


{% endblock %}

debts/templates/debts/new_transaction.html
{% extends 'debts/base.html' %}
{% load crispy_forms_tags %}

{% block content %}

    <div class="row">
        <div class="col-12">

            <div class="text-small- text-muted mb-2">
                <a href="{% url 'home' %}">Home</a> /
                <span>
                    New Transaction
                    {% if transaction_type == 'single' %} "@{{ debtors.username }}" {% else %} "Group" {% endif %}
                </span>
            </div>

            <form method="POST">

                {% csrf_token %}

                <input type="hidden" name="transaction_type" value="{{ transaction_type }}">

                {{ form|crispy }}


                {% if transaction_type == 'single' %}

                    <div id="div_id_remarks" class="form-group">
                        <label for="id_remarks" class=" requiredField">
                            Transaction against <strong><u>{{ debtors.first_name}} {{ debtors.last_name }} (@{{ debtors.username }})</u></strong>
                        </label>
                        <input type="hidden" name="debtor_id" value="{{ debtors.id }}">
                    </div>

                {% else %}

                    <div id="div_id_remarks" class="form-group">
                        <label for="id_remarks" class=" requiredField">
                            Select Users <span class="asteriskField">*</span>
                        </label>
                        <div class="">

                            <select name="debtor_id" id="debtor_id" class="form-control select2" required multiple>
                                {% for debtor in debtors %}
                                    <option value="{{ debtor.id }}">{{ debtor.first_name }} {{ debtor.last_name }} @{{ debtor.username }}</option>
                                {% endfor %}
                            </select>

                        </div>
                    </div>

                {% endif %}
                <hr>

                <a href="{% url 'home' %}" class="btn btn-warning text-white">
                    <i class="fa fa-arrow-left"></i> Cancel
                </a>

                <button class="btn btn-info text-white" type="submit">
                    <i class="fa fa-save"></i> Save Member
                </button>

            </form>



        </div>
    </div>


{% endblock %}

debts/templates/debts/transaction_form.html
{% extends 'debts/base.html' %}
{% load crispy_forms_tags %}

{% block content %}

    <div class="row">
        <div class="col-12">

            <div class="text-small- text-muted mb-2">
                <a href="{% url 'home' %}">Home</a> /
                <span>
                    New Transaction
                    {% if transaction_mode == 'single' %} "@{{ debtors.username }}" {% else %} "Group" {% endif %}
                </span>
            </div>

            <form method="POST">

                {% csrf_token %}

                <input type="hidden" name="transaction_mode" value="{{ transaction_mode }}">

                {{ form|crispy }}


                {% if transaction_mode == 'single' %}

                    <div id="div_id_remarks" class="form-group">
                        <label for="id_remarks" class=" requiredField">
                            Transaction against <strong><u>{{ debtors.first_name}} {{ debtors.last_name }} (@{{ debtors.username }})</u></strong>
                        </label>
                        <input type="hidden" name="debtor_id" value="{{ debtors.id }}">
                    </div>

                {% else %}

                    <div id="div_id_remarks" class="form-group">
                        <label for="id_remarks" class=" requiredField">
                            Select Users <span class="asteriskField">*</span>
                        </label>

                        <div class="row">

                            <!--<select name="debtor_id" id="debtor_id" class="form-control select2" required multiple>
                                {% for debtor in debtors %}
                                    <option value="{{ debtor.id }}">{{ debtor.first_name }} {{ debtor.last_name }} @{{ debtor.username }}</option>
                                {% endfor %}
                            </select>-->





                            {% for debtor in debtors %}
                                <div class="col-md-12 mb-1">
                                <input type="checkbox" name="debtor_id" value="{{ debtor.id }}" id="debtor_id_{{ debtor.id }}">
                                <label for="debtor_id_{{ debtor.id }}">
                                    <strong>{{ debtor.first_name }} {{ debtor.last_name }} @{{ debtor.username }}</strong>
                                </label>
                                 </div>
                            {% endfor %}
                        </div>
                    </div>

                {% endif %}
                <hr>

                <a href="{% url 'home' %}" class="btn btn-warning text-white">
                    <i class="fa fa-arrow-left"></i> Cancel
                </a>

                <button class="btn btn-info text-white" type="submit">
                    <i class="fa fa-save"></i> Save Transaction
                </button>

            </form>



        </div>
    </div>


{% endblock %}